#!/usr/bin/env python3
"""Developer tool that (re)generates the typed API wrappers.

This script parses ``API_doc.json`` (the IceWarp Maintenance API OpenAPI
export) and regenerates:

* ``src/icewarp_api/generated/*.py`` - one module per API category/tag, each
  containing a class with one typed, documented method per endpoint.
* ``src/icewarp_api/generated/raw_api.py`` - :class:`IceWarpRawAPI`, which
  wires the low level :class:`IceWarpClient` together with all of the
  generated category classes plus the generic ``call()`` escape hatch. This
  is exposed as ``IceWarpAPI.iw`` (see ``src/icewarp_api/api.py``, which is
  hand-written and NOT regenerated by this script - that's where curated,
  higher-level helpers belong).

It is a *development* tool, not shipped as part of the installed package.
Re-run it whenever ``API_doc.json`` changes::

    python scripts/generate_client.py

The generated code is committed to the repository so that consumers of the
published package do not need ``API_doc.json`` at install/run time.
"""

from __future__ import annotations

import json
import keyword
import re
import textwrap
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parent.parent
API_DOC = ROOT / "API_doc.json"
OUT_DIR = ROOT / "src" / "icewarp_api" / "generated"
RAW_API_FILE = OUT_DIR / "raw_api.py"

# tag (as it appears in API_doc.json) -> (module_name, class_name, facade_attribute)
TAG_INFO: Dict[str, tuple] = {
    "Session related methods": ("session_methods", "SessionMethods", "sessions"),
    "OAuth related methods": ("oauth", "OauthMethods", "oauth"),
    "Account related methods": ("account", "AccountMethods", "accounts"),
    "SignUp related methods": ("signup", "SignupMethods", "signup"),
    "Rule related methods": ("rule", "RuleMethods", "rules"),
    "Domain related methods": ("domain", "DomainMethods", "domains"),
    "Device related methods": ("device", "DeviceMethods", "devices"),
    "Account mebers related methods": (
        "account_members",
        "AccountMembersMethods",
        "account_members",
    ),
    "Service &amp; statistics related methods": (
        "service_statistics",
        "ServiceStatisticsMethods",
        "service",
    ),
    "Certificate related methods": ("certificate", "CertificateMethods", "certificates"),
    "Spam queues related methods": ("spam_queues", "SpamQueuesMethods", "spam_queues"),
    "Server related methods": ("server", "ServerMethods", "server"),
    "SmartDiscover related methods": (
        "smart_discover",
        "SmartDiscoverMethods",
        "smart_discover",
    ),
    "License related methods": ("license_methods", "LicenseMethods", "license"),
}

PY_TYPE = {"string": "str", "integer": "int", "object": "Any", "boolean": "bool"}

HEADER = '''"""Auto-generated by scripts/generate_client.py - do not edit by hand.

Typed wrappers for endpoints tagged {tag!r} in the IceWarp Maintenance API.
"""

from __future__ import annotations

from typing import Any, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from ..client import IceWarpClient


class {class_name}:
    """Typed wrappers for endpoints tagged {tag!r}."""

    def __init__(self, client: "IceWarpClient") -> None:
        self._client = client
'''


def to_snake_case(name: str) -> str:
    name = name.replace("OAuth", "Oauth").replace("SaaS", "Saas")
    name = name.replace("__", "_")
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s2 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1)
    return s2.replace("__", "_").lower()


def safe_identifier(name: str) -> str:
    if keyword.iskeyword(name) or keyword.issoftkeyword(name):
        return name + "_"
    return name


def load_endpoints() -> List[Dict[str, Any]]:
    data = json.loads(API_DOC.read_text(encoding="utf-8"))
    schemas = data["components"]["schemas"]
    endpoints = []
    for path, methods in data["paths"].items():
        detail = methods["post"]
        tag = (detail.get("tags") or ["Other"])[0]
        command_name = path.lstrip("/")
        method_name = to_snake_case(command_name)
        summary = (detail.get("summary") or "").strip()
        description = (detail.get("description") or "").strip()

        schema_ref = detail["requestBody"]["content"]["application/xml"]["schema"]["$ref"]
        schema = schemas[schema_ref.split("/")[-1]]
        commandparams = schema["properties"]["query"]["properties"].get("commandparams") or {}

        params = []
        for name, sub in (commandparams.get("properties") or {}).items():
            params.append({"name": name, "type": sub.get("type", "string")})

        endpoints.append(
            {
                "path": path,
                "command_name": command_name,
                "method_name": method_name,
                "tag": tag,
                "summary": summary,
                "description": description,
                "params": params,
            }
        )
    return endpoints


def build_doc_lines(ep: Dict[str, Any]) -> List[str]:
    lines: List[str] = []
    lines.append(ep["summary"] or f"Calls the {ep['command_name']} endpoint.")

    description = ep["description"]
    if description and description != ep["summary"]:
        lines.append("")
        for line in description.splitlines():
            lines.append(line.rstrip())

    lines.append("")
    lines.append(f"Endpoint: ``POST /{ep['command_name']}``")

    if ep["params"]:
        lines.append("")
        lines.append("Args:")
        for p in ep["params"]:
            lines.append(f"    {safe_identifier(p['name'])}: Maps to the ``{p['name']}`` request parameter.")

    lines.append("")
    lines.append("Returns:")
    lines.append(
        "    The parsed ``result`` value from the response - see "
        "``IceWarpClient.call`` for details."
    )

    # Trim leading/trailing blank lines and guard against stray triple quotes.
    while lines and lines[0] == "":
        lines.pop(0)
    while lines and lines[-1] == "":
        lines.pop()
    return [line.replace('"""', "'''") for line in lines]


def render_method(ep: Dict[str, Any]) -> str:
    args = ["self"]
    if ep["params"]:
        args.append("*")
    param_dict_lines = []
    for p in ep["params"]:
        ident = safe_identifier(p["name"])
        py_type = PY_TYPE.get(p["type"], "Any")
        args.append(f"{ident}: Optional[{py_type}] = None")
        param_dict_lines.append(f'            "{p["name"]}": {ident},')

    signature = ", ".join(args)
    doc_lines = build_doc_lines(ep)

    out = []
    out.append(f"    def {ep['method_name']}({signature}) -> Any:")
    out.append('        """' + doc_lines[0])
    for line in doc_lines[1:]:
        out.append(("        " + line).rstrip())
    out.append('        """')

    if param_dict_lines:
        out.append("        params = {")
        out.extend(param_dict_lines)
        out.append("        }")
        out.append(f'        return self._client.call("{ep["command_name"]}", **params)')
    else:
        out.append(f'        return self._client.call("{ep["command_name"]}")')

    out.append("")
    return "\n".join(out)


def generate_modules(endpoints: List[Dict[str, Any]]) -> Dict[str, tuple]:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    by_tag: Dict[str, List[Dict[str, Any]]] = {}
    for ep in endpoints:
        by_tag.setdefault(ep["tag"], []).append(ep)

    unknown_tags = set(by_tag) - set(TAG_INFO)
    if unknown_tags:
        raise SystemExit(f"Unknown tag(s) in API_doc.json, update TAG_INFO: {unknown_tags}")

    for tag, module_name, class_name, _attr in [
        (tag, *info) for tag, info in TAG_INFO.items()
    ]:
        eps = sorted(by_tag.get(tag, []), key=lambda e: e["method_name"])
        content = HEADER.format(tag=tag, class_name=class_name)
        if eps:
            content += "\n"
            content += "\n".join(render_method(ep) for ep in eps)
        else:
            content += "\n"
        (OUT_DIR / f"{module_name}.py").write_text(content, encoding="utf-8", newline="\n")

    init_lines = ['"""Auto-generated package: typed wrapper classes per API category."""', ""]
    for tag, (module_name, class_name, _attr) in TAG_INFO.items():
        init_lines.append(f"from .{module_name} import {class_name}")
    init_lines.append("from .raw_api import IceWarpRawAPI")
    init_lines.append("")
    init_lines.append("__all__ = [")
    for _tag, (_module_name, class_name, _attr) in TAG_INFO.items():
        init_lines.append(f'    "{class_name}",')
    init_lines.append('    "IceWarpRawAPI",')
    init_lines.append("]")
    (OUT_DIR / "__init__.py").write_text("\n".join(init_lines) + "\n", encoding="utf-8", newline="\n")

    return TAG_INFO


def generate_raw_api(tag_info: Dict[str, tuple]) -> None:
    lines = []
    lines.append('"""Auto-generated by scripts/generate_client.py - do not edit by hand.')
    lines.append("")
    lines.append("``IceWarpRawAPI`` (exposed as ``IceWarpAPI.iw``, see ``src/icewarp_api/api.py``)")
    lines.append("holds every raw, generated, 1:1 endpoint wrapper (``.iw.domains``,")
    lines.append("``.iw.accounts``, ..., plus the generic ``.iw.call()`` escape hatch) - see")
    lines.append("the sibling modules in this package for the underlying methods.")
    lines.append('"""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from typing import Any")
    lines.append("")
    lines.append("from ..client import IceWarpClient")
    for _tag, (module_name, class_name, _attr) in tag_info.items():
        lines.append(f"from .{module_name} import {class_name}")
    lines.append("")
    lines.append("")
    lines.append("class IceWarpRawAPI:")
    lines.append('    """Raw, generated, 1:1 access to every documented IceWarp API endpoint.')
    lines.append("")
    lines.append("    Exposed as ``IceWarpAPI.iw``. Every attribute here is either a typed")
    lines.append("    wrapper class generated from ``API_doc.json`` (grouped by category) or")
    lines.append("    the generic :meth:`call` escape hatch - nothing here is hand-curated:")
    lines.append("")
    for _tag, (_module_name, class_name, attr) in tag_info.items():
        lines.append(f"    * ``.{attr}`` - :class:`~icewarp_api.generated.{_module_name}.{class_name}`")
    lines.append('    """')
    lines.append("")
    lines.append("    def __init__(self, client: IceWarpClient) -> None:")
    lines.append("        self._client = client")
    for _tag, (_module_name, class_name, attr) in tag_info.items():
        lines.append(f"        self.{attr} = {class_name}(client)")
    lines.append("")
    lines.append("    def call(self, command_name: str, **params: Any) -> Any:")
    lines.append('        """Call any of the 174 documented endpoints directly by command name.')
    lines.append("")
    lines.append("        Useful as an escape hatch for endpoints where you prefer not to use")
    lines.append("        the typed wrapper, or for calling new endpoints before this library")
    lines.append('        has been regenerated against an updated API_doc.json.')
    lines.append('        """')
    lines.append("        return self._client.call(command_name, **params)")
    lines.append("")

    RAW_API_FILE.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> None:
    endpoints = load_endpoints()
    print(f"Loaded {len(endpoints)} endpoints from {API_DOC.name}")
    tag_info = generate_modules(endpoints)
    generate_raw_api(tag_info)
    print(f"Generated {len(tag_info)} category modules in {OUT_DIR}")
    print(f"Generated raw API facade: {RAW_API_FILE}")
    print("Note: src/icewarp_api/api.py (IceWarpAPI) is hand-written and was NOT touched.")


if __name__ == "__main__":
    main()

